//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonApp.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What item do you want to acces?.
        /// </summary>
        internal static string accesItem {
            get {
                return ResourceManager.GetString("accesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  isn&apos;t a valid number please fill in a number.
        /// </summary>
        internal static string accesNaN {
            get {
                return ResourceManager.GetString("accesNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range.
        /// </summary>
        internal static string accesOutofRange {
            get {
                return ResourceManager.GetString("accesOutofRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Alternative name of the show if it has one.
        /// </summary>
        internal static string addAlternative {
            get {
                return ResourceManager.GetString("addAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding complete.
        /// </summary>
        internal static string addComplete {
            get {
                return ResourceManager.GetString("addComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of the show.
        /// </summary>
        internal static string addDescription {
            get {
                return ResourceManager.GetString("addDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter if the show has an ending.
        /// </summary>
        internal static string addEnding {
            get {
                return ResourceManager.GetString("addEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter its English name of the show.
        /// </summary>
        internal static string addEnglish {
            get {
                return ResourceManager.GetString("addEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of episodes of the show.
        /// </summary>
        internal static string addEpisodes {
            get {
                return ResourceManager.GetString("addEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the genres of the show.
        /// </summary>
        internal static string addGenres {
            get {
                return ResourceManager.GetString("addGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new item.
        /// </summary>
        internal static string addNewItem {
            get {
                return ResourceManager.GetString("addNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any additional notes about the show.
        /// </summary>
        internal static string addNotes {
            get {
                return ResourceManager.GetString("addNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the runtime of a single episode.
        /// </summary>
        internal static string addRuntime {
            get {
                return ResourceManager.GetString("addRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the score of the show.
        /// </summary>
        internal static string addScore {
            get {
                return ResourceManager.GetString("addScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter if you have already watched it.
        /// </summary>
        internal static string addWatched {
            get {
                return ResourceManager.GetString("addWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the alternative name of the show.
        /// </summary>
        internal static string editAlternative {
            get {
                return ResourceManager.GetString("editAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing complete.
        /// </summary>
        internal static string editComplete {
            get {
                return ResourceManager.GetString("editComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of the show.
        /// </summary>
        internal static string editDescription {
            get {
                return ResourceManager.GetString("editDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter wether the show has an ending or not.
        /// </summary>
        internal static string editEnding {
            get {
                return ResourceManager.GetString("editEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the english name of the show.
        /// </summary>
        internal static string editEnglish {
            get {
                return ResourceManager.GetString("editEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of episodes of the show.
        /// </summary>
        internal static string editEpisodes {
            get {
                return ResourceManager.GetString("editEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What field do you want to edit?.
        /// </summary>
        internal static string editField {
            get {
                return ResourceManager.GetString("editField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter teh genres of the show.
        /// </summary>
        internal static string editGenres {
            get {
                return ResourceManager.GetString("editGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter additional notes about the show.
        /// </summary>
        internal static string editNotes {
            get {
                return ResourceManager.GetString("editNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;alternative\&quot; for editing the alternative name\n\&quot;english\&quot; for editing the english name\n\&quot;episodes\&quot; for editing the amount of episodes\n\&quot;description\&quot; for editing the description\n\&quot;genres\&quot; for editing its genres\n\&quot;notes\&quot; for editing the notes\n\&quot;score\&quot; for editing the score\n\&quot;runtime\&quot; for editing the runtime\n\&quot;watched\&quot; for editing if you have watched it\n\&quot;ending\&quot; for editing if it has an ending\n\&quot;exit\&quot; for stop editing.
        /// </summary>
        internal static string editOptions {
            get {
                return ResourceManager.GetString("editOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the runtime per episode.
        /// </summary>
        internal static string editRuntime {
            get {
                return ResourceManager.GetString("editRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the scoring of the show.
        /// </summary>
        internal static string editScore {
            get {
                return ResourceManager.GetString("editScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter wether you have watched the show or not.
        /// </summary>
        internal static string editWatched {
            get {
                return ResourceManager.GetString("editWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding.
        /// </summary>
        internal static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling the search.
        /// </summary>
        internal static string findCancel {
            get {
                return ResourceManager.GetString("findCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to search using: no ?.
        /// </summary>
        internal static string findConfirmNo {
            get {
                return ResourceManager.GetString("findConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to search using: {0} ?.
        /// </summary>
        internal static string findConfirmTerm {
            get {
                return ResourceManager.GetString("findConfirmTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to search using: yes ?.
        /// </summary>
        internal static string findConfirmYes {
            get {
                return ResourceManager.GetString("findConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type \&quot;y\&quot; to continue.
        /// </summary>
        internal static string findContinue {
            get {
                return ResourceManager.GetString("findContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it have an ending?.
        /// </summary>
        internal static string findEnding {
            get {
                return ResourceManager.GetString("findEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What field do you want to search in?.
        /// </summary>
        internal static string findField {
            get {
                return ResourceManager.GetString("findField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There hasn&apos;t been any item found in {0} with the term {1} do you want to use a different term?.
        /// </summary>
        internal static string findNoResult {
            get {
                return ResourceManager.GetString("findNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;alternative\&quot; for looking for the alternative name\n\&quot;english\&quot; for looking for the english name\n\&quot;genres\&quot; for looking in the genres \n\&quot;description\&quot; for looking in the description \n\&quot;watched\&quot; for looking if you watched it \n\&quot;ending\&quot; for looking if it has an ending \n\&quot;exit\&quot; to stop searching.
        /// </summary>
        internal static string findOptions {
            get {
                return ResourceManager.GetString("findOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On what do you want to search?.
        /// </summary>
        internal static string findOther {
            get {
                return ResourceManager.GetString("findOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you watched it?.
        /// </summary>
        internal static string findWatched {
            get {
                return ResourceManager.GetString("findWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  isn&apos;t a valid command please enter a valid command.
        /// </summary>
        internal static string invalidCommand {
            get {
                return ResourceManager.GetString("invalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading complete.
        /// </summary>
        internal static string loadComplete {
            get {
                return ResourceManager.GetString("loadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the file?.
        /// </summary>
        internal static string loadFileName {
            get {
                return ResourceManager.GetString("loadFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;add\&quot; for adding a new item\n&quot;\&quot;remove\&quot; for removing an excisting item\n\&quot;find\&quot; for finding items\n\&quot;edit\&quot; for editing an excisting item\n\&quot;save\&quot; for saving the excisting items\n\&quot;load\&quot; for loading items from a file\n\&quot;exit\&quot; exit for stopping the program\n.
        /// </summary>
        internal static string mainOptions {
            get {
                return ResourceManager.GetString("mainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize a show since it doesn&apos;t have a name.
        /// </summary>
        internal static string noName {
            get {
                return ResourceManager.GetString("noName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Program.
        /// </summary>
        internal static string programEnd {
            get {
                return ResourceManager.GetString("programEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Program.
        /// </summary>
        internal static string programStart {
            get {
                return ResourceManager.GetString("programStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling the removal.
        /// </summary>
        internal static string removeCancel {
            get {
                return ResourceManager.GetString("removeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing complete.
        /// </summary>
        internal static string removeComplete {
            get {
                return ResourceManager.GetString("removeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove:.
        /// </summary>
        internal static string removeConfirm {
            get {
                return ResourceManager.GetString("removeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving complete.
        /// </summary>
        internal static string saveComplete {
            get {
                return ResourceManager.GetString("saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should the file be named?.
        /// </summary>
        internal static string saveFileName {
            get {
                return ResourceManager.GetString("saveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative name of the show : .
        /// </summary>
        internal static string showAlternative {
            get {
                return ResourceManager.GetString("showAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : .
        /// </summary>
        internal static string showDescription {
            get {
                return ResourceManager.GetString("showDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has an ending : .
        /// </summary>
        internal static string showEnding {
            get {
                return ResourceManager.GetString("showEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name of the show : .
        /// </summary>
        internal static string showEnglish {
            get {
                return ResourceManager.GetString("showEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Episodes : .
        /// </summary>
        internal static string showEpisodes {
            get {
                return ResourceManager.GetString("showEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres : .
        /// </summary>
        internal static string showGenres {
            get {
                return ResourceManager.GetString("showGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes : .
        /// </summary>
        internal static string showNotes {
            get {
                return ResourceManager.GetString("showNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total runtime is {0}:{1} or {2} minutes per episode.
        /// </summary>
        internal static string showRuntime {
            get {
                return ResourceManager.GetString("showRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score : .
        /// </summary>
        internal static string showScore {
            get {
                return ResourceManager.GetString("showScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched : .
        /// </summary>
        internal static string showWatched {
            get {
                return ResourceManager.GetString("showWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been changed but not saved, do you want to save it?.
        /// </summary>
        internal static string unsavedChanges {
            get {
                return ResourceManager.GetString("unsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No.
        /// </summary>
        internal static string yesNo {
            get {
                return ResourceManager.GetString("yesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No / Other.
        /// </summary>
        internal static string yesNoOther {
            get {
                return ResourceManager.GetString("yesNoOther", resourceCulture);
            }
        }
    }
}
